config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :musics, :composers, :music, :welcome, :charges, :tracks, :books, :cart, :cart_items, :addresses

  root 'welcome#index'

	get 'admin' => 'welcome#admin'
	get 'admin/music/:id/tracks' => 'welcome#tracks', as: :admin_tracks
	get 'admin/address-book/user/:id' => 'welcome#address_book', as: :admin_address_book
	get 'admin/user/:id/edit' => 'welcome#admin_edit_user', as: :admin_edit_user
	patch 'admin/user/:id/update' => 'welcome#admin_user_update', as: :admin_user_update
	match 'admin/user/:id' => 'welcome#user_destroy', :via => :delete, as: :admin_destroy_user
	get 'orders/admin/:id/ship' => 'welcome#ship_order', as: :ship_order
	get 'orders/user' => 'welcome#orders', as: :user_orders
	get 'orders/admin' => 'welcome#admin_orders', as: :admin_orders
	get 'orders/admin/order/:id' => 'welcome#admin_view_order', as: :admin_view_order

  get 'users/:id/profile' => 'welcome#user_profile', as: :user_profile
	get 'cart_items' => 'cartitem#create', as: :add_to_cart
	get 'update_cart_item' => 'cartitem#update', as: :update_cart_item

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	before_action :authenticate_user!, only: [:admin, :address_book, :orders, :admin_orders, :admin_edit_user, :user_destroy, :admin_user_update, :tracks]
	before_action :verify_admin!, only: [:admin, :admin_orders, :admin_edit_user, :user_destroy, :admin_user_update, :tracks]
	
	def address_book
		@user = User.find(params[:id])
		@addresses = Address.where(:user_id => params[:id])
	end

	def admin
		@books = Book.all.order(:pubdate)
		@music = Music.all.order(:released)
		@composers = Composer.all.order(:lname, :fname)
		@users = User.all.order(:lname)
		@admin = User.where(:admin => true).order(:lname)
	end
	
	def admin_orders
		@open = Cart.where(:status => 'open').limit(50).order("created_at DESC")
		@orders = Cart.where(:status => 'processed').order("shipped ASC")
		@filled = Cart.where(:status => 'shipped').limit(50).order("shipped DESC")
	end
	
	def orders
		@orders = Cart.where(:user_id => current_user.id).order("placed DESC")
	end
	
	def admin_view_order
		@order = Cart.find(params[:id])
	end
	
	def ship_order
		@order = Cart.find(params[:id])
		@order.update_attribute("shipped", DateTime.now)
		@order.update_attribute("status", 'shipped')
		@order.update_attribute("admin", current_user.id)
		
		redirect_to admin_orders_path
	end
	
	def admin_edit_user
		@selected_user = User.find(params[:id])
	end
	
	def user_destroy
		@selected_user = User.find(params[:id])
		@selected_user.delete
		@useraddresses = Address.where(:user_id => @selected_user.id)
		@useraddresses.delete
		redirect_to admin_path
	end
	
	def admin_user_update
		@selected_user = User.find(params[:id])
		if params[:user][:password].blank?
			params[:user].delete(:password)
			params[:user].delete(:password_confirmation)
		end
		if @selected_user.update(selected_user_params)
			flash[:success] = "User successfully updated"
			redirect_to admin_path
		else
			flash[:error] = @selected_user.errors
			render :admin_edit_user
		end
	end
	
	def tracks
		@music = Music.find(params[:id])
		@tracks = @music.tracks.order(:number)
	end
	
	def user_profile
		@user = User.find(params[:id])
		@orders = Cart.where(:user_id => @user.id).where(:status != "open" && :status != nil)
	end
	private
	
		def selected_user_params
			params.require(:user).permit(:fname, :lname, :company, :email, :password, :password_confirmation, :admin)
		end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def cartitems(cart)
		items = CartItem.where(:cart_id => cart.id).order(:created_at)
	end
	
	def item_count(cart)
		items = CartItem.where(:cart_id => cart.id)
		
		count = 0
		items.each do |i|
			count += i.quantity
		end
		
		return count
	end
	
	def admin_initials(order)
		admin = User.find(order.admin)
		
		return admin.fname[0,1].titleize + admin.lname[0,1].titleize
	end

end

app/views/welcome/address_book.html.erb
<%= render "layouts/nav" %>

	<table id="index_title">
		<tr><td>
			<h2>Address Book<span style="font-size: .8em; opacity: .8;"> for <%= @user.full_name %></span></h2>
		</td><td>
			<span style="font-size: .8em; opacity: .8;">User #<%= @user.id %></span>
		</td></tr>
	</table>
	
	<ul id="index_ul">
		<% @addresses.each do |address| %>
			<li>
				<div class="index_block">
					<div class="index_address_details">
						<div class="index_address_title"><%= address.name %></div>
						<% if address.company.present? %>
								<%= address.company %><br />
							<% end %>
							<%= address.address1 %><br />
							<% if address.address2.present? %>
								<%= address.address2 %><br />
							<% end %>
							<%= address.city %>, <%= address.state %> <%= address.zip %><br />
							<% if address.phone.present? %>
								<%= address.phone %><br />
							<% end %>
						</div>
						<div class="inline-block">
							<%= link_to "Edit", edit_address_path(address), method: :get, :class => "address_link" %>
							<%= link_to "Delete", address_path(address), method: :delete, data: {confirm: "Are you sure you want to delete this address?"}, :class => "address_link" %>
						</div>
						<br />
						<i style="opacity: .8;">Address # <%= address.id %></i>
						<br />
					</div>
				</div>
			</li>
		<% end %>
		<li>
			<%= link_to "New Address", new_address_path %>
		</li>
	</ul>

app/views/welcome/admin.html.erb
<%= render "layouts/nav" %>

<table id="index_title">
	<tr><td>
		<h2 style="display: inline-block; margin-bottom: 0px;">Admin</h2><br />
		<i>Hello, <%= current_user.fname %><br /><%= link_to "Edit Account", edit_user_registration_path(current_user) %> &nbsp;| &nbsp;<%= link_to "Logout", destroy_user_session_path, :method => :delete %></i>
	</td><td>
	<%= link_to "Orders", admin_orders_path, :style => 'font-size: .9em;' %>
	</td></tr>
</table>

	<!-------------- Authors/Artists -------------!>
			<div class="admin_main">
				<h2>Authors/Artists <span style="font-size: .7em;">(<%= @composers.count %>)</span></h2>
				<%= link_to "Add Author/Artist", new_composer_path %>
				<ul class="admin_list">
					<% @composers.each do |composer| %>
						<li>
							<div class="admin_item_div admin_item_title" %>
								<%= composer.full_name %>
							</div>
							<div class="admin_item_div">
								<%= composer.city + ", " + composer.state %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Page", composer_path(composer), :class => "admin_show_button", method: :get %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Edit", edit_composer_path(composer), :class => "admin_edit_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>


	<!-------------- Books -------------!>
			<div class="admin_main">
				<h2>Books <span style="font-size: .7em;">(<%= @books.count %>)</span></h2>
				<%= link_to "Add Book", new_book_path %>
				<ul class="admin_list">
					<% @books.each do |book| %>
						<li>
							<div class="admin_item_div admin_item_title">
								<%= book.title %>
							</div>
							<div class="admin_item_div">
								<%= book.composers.each.map{|c| c.full_name}.join(", ") %>
							</div>
							<div class="admin_item_div">
								<%= usd(book.price) %>
							</div>
							<div class="admin_item_div">
								<%= book.stock %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Book", book_path(book), :class => "admin_show_button", method: :get %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Edit", edit_book_path(book), :class => "admin_edit_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>
	
	<!-------------- Music -------------!>
			<div class="admin_main">
				<h2>Music <span style="font-size: .7em;">(<%= @music.count %>)</span></h2>
				<%= link_to "Add Album", new_music_path %>
				<ul class="admin_list">
					<% @music.each do |music| %>
						<li>
							<div class="admin_item_div admin_item_title">
								<%= music.title %>
							</div>
							<div class="admin_item_div">
								<%= usd(music.price) %>
							</div>
							<div class="admin_item_div">
								<%= music.stock %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Tracks", admin_tracks_url(id: music.id), :class => "admin_toggle_button", method: :get %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Album", music_path(music), :class => "admin_show_button", method: :get %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Edit", edit_music_path(music), :class => "admin_edit_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>

			
	<!------------- Users -------------!>
				<div class="admin_main">
					<h2>Customers <span style="font-size: .7em;">(<%= @users.count %>)</span></h2>
					<ul class="admin_list">
						<% @users.each do |user| %>
							<li>
								<div class="admin_item_div admin_item_title">
									<%= user.lname + ", " + user.fname%>
								</div>
								<div class="admin_item_div">
									<%= user.email %>
								</div>
								<div class="admin_edit_div">
									<%= button_to "Address Book", admin_address_book_path(user), :class => "admin_toggle_button", method: :get %>
								</div>
								<div class="admin_edit_div">
									<%= button_to "Edit", admin_edit_user_path(user), :class => "admin_edit_button", method: :get %>
								</div>
							</li>
						<% end %>
					</ul>
				</div>
				
				
	<!------------- Admin -------------!>
			<div class="admin_main">
				<h2>Administrators <span style="font-size: .7em;">(<%= @admin.count %>)</span></h2>
				<ul class="admin_list">
					<% @admin.each do |admin| %>
						<li>
							<div class="admin_item_div admin_item_title">
								<%= admin.fname + " " + admin.lname%>
							</div>
							<div class="admin_item_div">
								<%= admin.email %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Edit", edit_user_registration_path(admin), :class => "admin_toggle_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>

app/views/welcome/admin_edit_user.html.erb
<%= render "layouts/nav" %>

<div id="main">

	<h2>Edit <%= @selected_user.full_name %></h2>

	<%= form_for(@selected_user, url: admin_user_update_path) do |f| %>
	  <ul>
	<% @selected_user.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>

	  <p class="form_liner">
	    <%= f.label :email %>
	    <%= f.email_field :email, autofocus: true %>
	  </p>

	  <p class="form_liner">
	    <%= f.label :password, "Change Password" %>
	    <%= f.password_field :password, autocomplete: "off", :placeholder => "(leave blank if you don't want to change it)" %>
	  </p>

	  <p class="form_liner">
	    <%= f.label :password_confirmation %>
	    <%= f.password_field :password_confirmation, autocomplete: "off" %>
	  </p>

<% if current_user.admin %>
	 <p class="form_liner checkbox_liner">
		<%= f.label :admin %>
		<%= f.check_box :admin %>
	</p>

<% end %>

	<p class="form_liner">
				<%= f.label :first_name %>
				<%= f.text_field :fname %>
			</p>
			
			<p class="form_liner">
				<%= f.label :last_name %>
				<%= f.text_field :lname %>
			</p>

		 	<p class="form_liner">
				<%= f.label :company %>
				<%= f.text_field :company %>
			</p>

	  <p class="form_liner">
	    <%= f.submit "Update" %>
	  </p>
	<% end %>

	<p class="form_liner">
		<%= button_to "Cancel Account", admin_destroy_user_path(@selected_user), method: :delete, data: { confirm: "Are you sure you want to delete this account? This will remove the account and all addresses associated with it and cannot be undone." }, :class => 'red_button' %>
	</p>
	
</div>

app/views/welcome/admin_orders.html.erb
<%= render "layouts/nav" %>

<table id="index_title">
	<tr><td>
		<h2 style="display: inline-block;">Orders</h2><br />
	</td><td>
		<%= link_to "Admin Dashboard", admin_path, :style => 'font-size: .9em;' %>
	</td></tr>
</table>

	<!-------------- Pending Orders -------------!>
			<div class="admin_main">
				<h2>New Orders <span style="font-size: .7em;">(<%= @orders.count %>)</span></h2>
				<ul class="admin_list">
					<% @orders.each do |order| %>
						<li>
							<div class="admin_item_div admin_item_title" %>
								Order #<%= order.id %>
							</div>
							<div class="admin_item_div">
								<%= order.placed.strftime("%a, %b %d, %Y") %>
							</div>
							<div class="admin_item_div">
								<% identify_address(order.address_id) %>
								<%= @address.city + ", " + @address.state %>
							</div>
							<div class="admin_item_div">
								<%= item_count(order) %> item(s)
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Details", admin_view_order_path(order), :class => "admin_toggle_button", method: :get %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "Change status to 'Shipped'", ship_order_path(order), :class => "admin_show_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>
			
			
<!-------------- Shipped Orders -------------!>
			<div class="admin_main">
				<h2>Filled Orders <span style="font-size: .7em;">(<%= @filled.count %>)</span></h2>
				<ul class="admin_list">
					<% @filled.each do |order| %>
						<li>
							<div class="admin_item_div admin_item_title" %>
								Order #<%= order.id %>
							</div>
							<div class="admin_item_div">
								<%= order.shipped.strftime("%a, %b %d, %Y") %>
							</div>
							<div class="admin_item_div">
								<%= link_to admin_initials(order), edit_user_registration_path(order.admin) %>
							</div>
							<div class="admin_item_div">
								<% identify_address(order.address_id) %>
								<%= @address.city + ", " + @address.state %>
							</div>
							<div class="admin_item_div">
								<%= item_count(order) %> item(s)
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Details", admin_view_order_path(order), :class => "admin_toggle_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>
			
<!-------------- Open Carts -------------!>
			<div class="admin_main">
				<h2>Open Carts <span style="font-size: .7em;">(<%= @open.count %>)</span></h2>
				<ul class="admin_list">
					<% @open.each do |order| %>
						<li>
							<div class="admin_item_div admin_item_title" %>
								Order #<%= order.id %>
							</div>
							<div class="admin_item_div">
								<%= item_count(order) %> item(s)
							</div>
							<% carttotal(order) %>
							<div class="admin_item_div">
								<%= usd(@carttotal) %>
							</div>
							<div class="admin_edit_div">
								<%= button_to "View Details", admin_view_order_path(order), :class => "admin_toggle_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>

app/views/welcome/admin_view_order.html.erb
<%= render "layouts/nav" %>

<div id="index_title">
	<h2 style="display: inline-block; margin-bottom: 0px;">Orders</h2>
</div>

	<!-------------- Orders -------------!>
		<div id="main">
			<div class="order_show_specifics">
				Order #<%= @order.id %><br />
				Status: <%= @order.status.titleize %><br />
				<% if @order.placed %>
					Placed: <%= @order.placed.strftime("%a, %b %d, %y - %l:%M %p") %><br />
				<% end %>
				<% if @order.shipped %>
					Shipped: <%= @order.shipped.strftime("%a, %b %d, %y - %l:%M %p") %>
				<% end %>
				
			</div>
			<table id="checkout_products">
				<tr>
					<th>Item</th>
					<th>Price Per Unit</th>
					<th>Quantity</th>
					<th>Price</th>
				</tr>
				<% cartitems(@order).each do |item| %>
					<tr>
						<% identify_product(item.product_id) %>
						<td class="title_col">&nbsp;&nbsp;<%= @product.title + " by " + @product.composers.map {|c| c.full_name}.join(", ") %></td>
						<td><%= usd(@product.price) %></td>
						<td style="height: 30px;"><%= item.quantity %></td>
						<td><%= usd(item.quantity.to_int * @product.price.to_int) %></td>
					</tr>
				<% end %>
				<% carttotal(@order) %>
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Cart Total</td>
					<td><%= usd(@carttotal) %></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title cart_sub_title">Tax</td>
					<td class="cart_sub_title"><%= usd(@tax) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Subtotal</td>
					<td><%= usd(@subtotal) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title cart_sub_title">Shipping</td>
					<td class="cart_sub_title"><%= usd(@shipping) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Total</td>
					<td><%= usd(@final) %></td>
					<td></td>
					<td></td>
				</tr>	

				
			</table>
			<% if @order.address_id %>
			Ship To:<br /><br />
			<% identify_address(@order.address_id) %>
			<div class="index_address_title"><%= @address.name %></div><br/ >
			<% if @address.company.present? %>
					<%= @address.company %><br />
				<% end %>
				<%= @address.address1 %><br />
				<% if @address.address2.present? %>
					<%= @address.address2 %><br />
				<% end %>
				<%= @address.city %>, <%= @address.state %> <%= @address.zip %><br />
				<% if @address.phone.present? %>
					<%= @address.phone %><br />
				<% end %>
			<% end %>
				
		</div>

app/views/welcome/index.html.erb
<div id="welcome_nav_wrapper">
	<%= link_to "Books", books_path, :class => 'nav_element', :id => 'welcome_books' %>
	<%= link_to image_tag("logo.png", :id => 'welcome_logo'), root_path %>
	<%= link_to "Music", musics_path, :class => 'nav_element', :id => 'welcome_music' %>
</div>

<div id="welcome_admin">
	<%= link_to "Contact Waller-Hill Publishing", "mailto:wallerhillpublishing@gmail.com" %>&nbsp;&nbsp;|&nbsp;&nbsp;
	<%= link_to "Admin", admin_path %>
</div>

app/views/welcome/orders.html.erb
<%= render "layouts/nav" %>

<div id="index_title">
	<h2 style="display: inline-block; margin-bottom: 0px;">Orders</h2>
</div>

	<!-------------- Orders -------------!>
	<% @orders.each do |order| %>
		<div id="main">
			<div class="order_show_specifics">
				Order #<%= order.id %><br />
				Status: <%= order.status.titleize %><br />
				Placed: <%= order.placed.strftime("%a, %b %d, %Y") %><br />
				<% if order.shipped %>
					Shipped: <%= order.shipped.strftime("%a, %b %d, %Y") %>
				<% end %>
				
			</div>
			<table id="checkout_products">
				<tr>
					<th>Item</th>
					<th>Price Per Unit</th>
					<th>Quantity</th>
					<th>Price</th>
				</tr>
				<% cartitems(order).each do |item| %>
					<tr>
						<% identify_product(item.product_id) %>
						<td class="title_col">&nbsp;&nbsp;<%= @product.title + " by " + @product.composers.map {|c| c.full_name}.join(", ") %></td>
						<td><%= usd(@product.price) %></td>
						<td style="height: 30px;"><%= item.quantity %></td>
						<td><%= usd(item.quantity.to_int * @product.price.to_int) %></td>
					</tr>
				<% end %>
				<% carttotal(order) %>
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Cart Total</td>
					<td><%= usd(@carttotal) %></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title cart_sub_title">Tax</td>
					<td class="cart_sub_title"><%= usd(@tax) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Subtotal</td>
					<td><%= usd(@subtotal) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title cart_sub_title">Shipping</td>
					<td class="cart_sub_title"><%= usd(@shipping) %></td>
					<td></td>
					<td></td>
				</tr>	
				<tr>
					<td></td>
					<td></td>
					<td class="cart_total_title">Total</td>
					<td><%= usd(@final) %></td>
					<td></td>
					<td></td>
				</tr>	
				
			</table>
			
			Ship To:<br /><br />
			<% identify_address(order.address_id) %>
			<div class="index_address_title"><%= @address.name %></div><br/ >
			<% if @address.company.present? %>
					<%= @address.company %><br />
				<% end %>
				<%= @address.address1 %><br />
				<% if @address.address2.present? %>
					<%= @address.address2 %><br />
				<% end %>
				<%= @address.city %>, <%= @address.state %> <%= @address.zip %><br />
				<% if @address.phone.present? %>
					<%= @address.phone %><br />
				<% end %>
				
		</div>
	<% end %>

app/views/welcome/tracks.html.erb
<%= render "layouts/nav" %>

<div id="index_title">
	<h2 style="display: inline-block; margin-bottom: 0px;">Admin</h2><br />
	<i>Logged in as <%= current_user.email %><br /><%= link_to "Edit Account", user_registration_path(current_user) %> &nbsp;| &nbsp;<%= link_to "Logout", destroy_user_session_path, :method => :delete %></i>
</div>

		<!-------------- Music -------------!>
			<div class="admin_main">
				<h2><%= @music.title %></h2>
				<%= link_to "Add Track", new_track_path %>
				<ul class="admin_album_tracks">
					<% @tracks.each do |track| %>
						<li>
							<div class="admin_item_div">
								<%= track.number %> / <%= @music.tracks.count %>
							</div>
							<div class="admin_item_div admin_item_title">
								<%= track.title %>
							</div>
							<div class="admin_item_div">
								<%= seconds_to_time(track.length) %>
							</div>
							<% if track.ccli %>
								<div class="admin_item_div">
									<%= track.ccli %>
								</div>
							<% end %>
							<div class="admin_edit_div">
								<%= button_to "Edit", edit_track_path(track), :class => "admin_edit_button", method: :get %>
							</div>
						</li>
					<% end %>
				</ul>
			</div>

app/views/welcome/user_profile.html.erb
<%= render "layouts/nav" %>

<table id="index_title">
	<tr><td>
		<h2 style="display: inline-block; margin-bottom: 0px;">My Account</h2><br />
		<i>Hello, <%= current_user.fname %><br />
		<%= link_to "Logout", destroy_user_session_path, :method => :delete %></i>
	</td></tr>
</table>

<div id="main">
	<h2>Account</h2>
	<ul>
		<li>- <%= link_to "Edit Account", edit_user_registration_path(current_user) %></li>
		<li>- <%= link_to "View Address Book", addresses_path %></li>
		<li>- <%= link_to "View Orders", user_orders_path %></li>
	</ul>
</div>
	