config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :musics, :composers, :music, :welcome, :charges, :tracks, :books, :cart, :cart_items, :addresses

  root 'welcome#index'

	get 'admin' => 'welcome#admin'
	get 'admin/music/:id/tracks' => 'welcome#tracks', as: :admin_tracks
	get 'admin/address-book/user/:id' => 'welcome#address_book', as: :admin_address_book
	get 'admin/user/:id/edit' => 'welcome#admin_edit_user', as: :admin_edit_user
	patch 'admin/user/:id/update' => 'welcome#admin_user_update', as: :admin_user_update
	match 'admin/user/:id' => 'welcome#user_destroy', :via => :delete, as: :admin_destroy_user
	get 'orders/admin/:id/ship' => 'welcome#ship_order', as: :ship_order
	get 'orders/user' => 'welcome#orders', as: :user_orders
	get 'orders/admin' => 'welcome#admin_orders', as: :admin_orders
	get 'orders/admin/order/:id' => 'welcome#admin_view_order', as: :admin_view_order

  get 'users/:id/profile' => 'welcome#user_profile', as: :user_profile
	get 'cart_items' => 'cartitem#create', as: :add_to_cart
	get 'update_cart_item' => 'cartitem#update', as: :update_cart_item

end

app/models/music.rb
class Music < ActiveRecord::Base

	has_and_belongs_to_many :composers, join_table: "musics_composers"
	has_many :tracks
	
	has_attached_file :artwork, styles: { large: "900x809", medium: "185x166>", thumb: "120x108>" }, default_url: "/images/:style/missing.jpg"
	validates_attachment_content_type :artwork, content_type: /\Aimage\/.*\Z/
	
	validates_presence_of :title, :description, :released
	validates_uniqueness_of :title


end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	
	include MusicsHelper

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to new_track_path, notice: 'Music was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to admin_path, notice: 'Music was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end
end

app/helpers/musics_helper.rb
module MusicsHelper

	    def music_params
			params.require(:music).permit(:title, :desc, :released, :description, :barcode, :stock, :can_order, :digital, :physical, :itunes, :price, :artwork, :composer_ids => [])
	    end

end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <ul>
  <% @music.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p class="form_liner">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p class="form_liner">
    <%= f.label :artist, :class => "composers_label" %>
	<%= f.select(:composer_ids, Composer.all.collect {|c| [c.full_name, c.id]}, {},
								{:multiple => true,
								:size => 5}) %>
  </p>

  <p class="form_liner">
	<%= f.label :artwork %>
    <%= f.file_field :artwork %>
  </p>

  <p class="form_liner">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p class="form_liner">
    <%= f.label :release_date%>
    <%= f.date_select :released,
						:use_short_month => true,
						:start_year => 2013,
						:end_year => Date.today.year + 1,
						:order => [:month, :day, :year] %>
  </p>
  <p class="form_liner">
    <%= f.label :barcode %>
    <%= f.text_field :barcode, :maxlength => 13 %>
  </p>
  <p class="form_liner">
    <%= f.label :current_stock %>
    <%= f.text_field :stock %>
  </p>
  <p class="form_liner">
    <%= f.label :price, "Sell Price (in cents)" %>
    <%= f.text_field :price, :placeholder => "1499" %>
  </p>
  <p class="form_liner checkbox_liner">
    <%= f.check_box :can_order, :class => 'checkbox' %><%= f.label :music_can_be_ordered, "Available for purchase", :id => 'checkbox_label' %><br />
    <%= f.check_box :digital, :class => 'checkbox' %><%= f.label :digital, "Download available to purchase", :id => 'checkbox_label' %><br />
    <%= f.check_box :physical, :class => 'checkbox' %><%= f.label :physical, "Physical copy available for purchase", :id => 'checkbox_label' %><br />
  </p>
  <p class="form_liner">
    <%= f.submit(:class => "submit") %>
  </p>
<% end %>

app/views/musics/edit.html.erb
<%= render "layouts/nav" %>

<div id="main">
	<h2>Edit <%= @music.title %></h2>
	<%= render "form" %>
	<%= button_to "Delete Music", music_path(@music), method: :delete, data: {confirm: "Really delete this album? This action cannot be undone"}, :class => "red_button" %>
</div>

app/views/musics/index.html.erb
<%= render "layouts/nav" %>

<table id="index_title">
	<tr><td>
	<h2>Music</h2>
	</td><td>
	<%= link_to "Artists", {:controller => "composers", :action => "index", :view => "artists"} %>
	</td></tr>
</table>

	<ul id="index_ul">
		<% @musics.each do |music| %>
			<li>
				<div class="index_music">
				<%= link_to music_path(music) do %>
					<%= image_tag music.artwork.url(:medium), :class => 'show_music' %>
					<div class="index_music_details">
						<div class="index_music_title"><%= music.title %></div>
							Author: <i><%= raw(music.composers.map{|c| link_to c.full_name, composer_path(c)}.join(', ')) %></i><br />
							Release Date: <%= music.released.strftime("%b %d, %Y") %><br />
							Price: <%= usd(music.price) %><br />
							<br />
							<%= button_to "Add To Cart", add_to_cart_path(item: {:product_id => music.barcode, :quantity => 1, :cart_id => @cart.id}) %>
						</div>
					</div>
				<% end %>
			</li>
		<% end %>
	</ul>

app/views/musics/new.html.erb
<%= render "layouts/nav" %>

<div id="main">
	<h2>New Music</h2>
	<%= render "form" %>
</div>

app/views/musics/show.html.erb
<%= render "layouts/nav" %>

<div id="main">
	<%= image_tag @music.artwork.url(:medium), :class => 'show_music' %>
	<div id="show_music_details">
		<h2 class="show_title"><%= @music.title %></h2><br />
		Artist: <i><%= raw(@music.composers.map{|c| link_to c.full_name, composer_path(c)}.join(', ')) %></i><br />
		Release Date: <%= @music.released.strftime("%b %d, %Y") %><br />
		<% if @music.can_order == true && @music.physical == true %>
			<br /><br />
			<%= button_to "Add To Cart", add_to_cart_path(item: {:product_id => @music.barcode, :quantity => 1, :cart_id => @cart.id}) %>
		<% end %>
	</div>
	<div id="show_music_description">
		<%= raw @music.description %><br /><br />
		Tracks:<br />
			<% @music.tracks.order(:number).each do |t| %>
				<%= t.number %>. <%= t.title %><br />
			<% end %>
	</div>
	
</div>