config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :musics, :composers, :music, :welcome, :charges, :tracks, :books, :cart, :cart_items, :addresses

  root 'welcome#index'

	get 'admin' => 'welcome#admin'
	get 'admin/music/:id/tracks' => 'welcome#tracks', as: :admin_tracks
	get 'admin/address-book/user/:id' => 'welcome#address_book', as: :admin_address_book
	get 'admin/user/:id/edit' => 'welcome#admin_edit_user', as: :admin_edit_user
	patch 'admin/user/:id/update' => 'welcome#admin_user_update', as: :admin_user_update
	match 'admin/user/:id' => 'welcome#user_destroy', :via => :delete, as: :admin_destroy_user
	get 'orders/admin/:id/ship' => 'welcome#ship_order', as: :ship_order
	get 'orders/user' => 'welcome#orders', as: :user_orders
	get 'orders/admin' => 'welcome#admin_orders', as: :admin_orders
	get 'orders/admin/order/:id' => 'welcome#admin_view_order', as: :admin_view_order

  get 'users/:id/profile' => 'welcome#user_profile', as: :user_profile
	get 'cart_items' => 'cartitem#create', as: :add_to_cart
	get 'update_cart_item' => 'cartitem#update', as: :update_cart_item

end

app/models/charges.rb
class Address < ActiveRecord::Base

	accepts_nested_attributes_for :cart	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	include ChargesHelper

	def index
		@items = CartItem.where(:cart_id => @cart.id).order(:created_at)
		carttotal(@cart)
		
	end

	def new
		@items = CartItem.where(:cart_id => @cart.id).order(:created_at)
		if !current_user
			@newuser = User.new
			@newaddress = Address.new
		end
		@user_addresses = Address.where(:user => current_user)
	end

	def create
		
		if !current_user
			@newuser = User.new(user_params)
			if @newuser.save
				@newaddress = Address.new(address_params)
				@newaddress.user_id = @newuser.id
				@newaddress.save
				sign_in(:user, @newuser)
			else
				flash[:error] = @newuser.errors
				redirect_to new_charge_path
			end
			
			@cart.update_attribute("address_id", @newaddress.id)
		else
			@cart.update_attribute("address_id", params[:cart][:address_id])
		end

		@items = CartItem.where(:cart_id => @cart.id).order(:created_at)
	
		carttotal(@cart)
	
		total = @final.to_i

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	 if charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => total,
	    :description => 'Waller Hill Publishing',
	    :currency    => 'usd'
	  )
		@cart.update_attribute("status", "processed")
		@cart.update_attribute("user_id", current_user.id)
		@cart.update_attribute("placed", DateTime.now)
		
		OrderMailer.receipt(current_user, @cart, @items).deliver
		OrderMailer.orderNotification(current_user, @cart, @items).deliver
	else
		redirect_to new_charge_path
		flash[:error] = "An unknown error occured. Please try again. If the problem persists, please notify wallerhillpublishing@gmail.com"
	end

	@cart = Cart.create
	         session[:cart_id] = @cart.id

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path, :total => total
	end
	private
		
		def user_params
params.require(:user).permit(:email, :password, :password_confirmation, :admin, :fname, :lname, :company)
		end
		
		def address_params
			params.require(:address).permit(:name, :company, :address1, :address2, :city, :state, :zip, :country, :phone, :user_id)
		end
end

app/helpers/charges_helper.rb
module ChargesHelper

	def carttotal(cart)
		@carttotal = 0.00
		@total_items = 0
		
		items = CartItem.where(:cart_id => cart.id)
		
		items.each do |product|
			identify_product(product.product_id)
			
			@item_total = @product.price * product.quantity
			
			@total_items += product.quantity
			
			@carttotal += @item_total
		end
		@carttotal = @carttotal.to_f
		@taxrate = 0.08
		@tax = (@taxrate)*(@carttotal)
		@subtotal = (@carttotal)+(@tax)
		@shipping = (@total_items)*(300)
		@shipping = @shipping.to_f
		@final = @subtotal + @shipping
	end
end

app/views/charges/create.html.erb
<%= render "layouts/nav" %>

<div id="main">
	<h2>Success!</h2>
	Thank you for your purchase! Your order has been processed. A confirmation email will be sent to <%= current_user.email %>. You can view this order and your previous purchases in your account profile.<br /><br />
	<%= link_to "Account Profile", user_profile_path(current_user.id) %>
</div>

app/views/charges/new.html.erb
<%= render "layouts/nav" %>
<% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

<div id="main">
	<h2>Cart</h2>
	<% if !@items.first %>
		You've not added any items to Your cart
	<% else %>
		<table id="checkout_products">
			<tr>
				<th>Item</th>
				<th>Price Per Unit</th>
				<th>Quantity</th>
				<th>Price</th>
				<th></th>
			</tr>
			<% @items.each do |item| %>
				<tr>
					<% identify_product(item.product_id) %>
					<td class="title_col">&nbsp;&nbsp;<%= @product.title + " by " + @product.composers.map {|c| c.full_name}.join(", ") %></td>
					<td><%= usd(@product.price) %></td>
					<%= form_for(item) do %>
					<td><%= text_field_tag :quantity, item.quantity, :autocomplete => "off", :style => "background-color: inherit; text-align: center;" %></td>
					<td><%= usd(item.quantity.to_int * @product.price.to_int) %></td>
					<td><%= button_to "Update", update_cart_item_path(item), :class => "cart_item_button update_cart_item" %></td>
					<% end %>
					<td><%= button_to "Remove", cart_item_path(item), method: :delete, :class => "cart_item_button remove_cart_item" %></td>
				</tr>
			<% end %>
			<% carttotal(@cart) %>
			<tr>
				<td></td>
				<td></td>
				<td class="cart_total_title">Cart Total</td>
				<td><%= usd(@carttotal) %></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td class="cart_total_title cart_sub_title">Tax</td>
				<td class="cart_sub_title"><%= usd(@tax) %></td>
				<td></td>
				<td></td>
			</tr>	
			<tr>
				<td></td>
				<td></td>
				<td class="cart_total_title">Subtotal</td>
				<td><%= usd(@subtotal) %></td>
				<td></td>
				<td></td>
			</tr>	
			<tr>
				<td></td>
				<td></td>
				<td class="cart_total_title cart_sub_title">Shipping</td>
				<td class="cart_sub_title"><%= usd(@shipping) %></td>
				<td></td>
				<td></td>
			</tr>	
			<tr>
				<td></td>
				<td></td>
				<td class="cart_total_title">Total</td>
				<td><%= usd(@final) %></td>
				<td></td>
				<td></td>
			</tr>	
		</table>

	<% if !current_user.present? %>
		<%= form_for(@newuser, url: charges_path) do |f| %>
		<h2>Create Account</h2>
			<p class="form_liner checkout">
				<%= f.label :first_name %>
				<%= f.text_field :fname %>

				<%= f.label :last_name %>
				<%= f.text_field :lname %>
			</p>

		 	<p class="form_liner checkout">
				<%= f.label :company %>
				<%= f.text_field :company %>
				
		    	<%= f.label :email %>
			    <%= f.email_field :email, autofocus: true %>
			</p>
			
			<p class="form_liner checkout">

				<%= f.label :password %>
		    	<%= f.password_field :password, autocomplete: "off" %>

				<%= f.label :password_confirmation %>
		    	<%= f.password_field :password_confirmation, autocomplete: "off" %>
			</p>
		
		<hr />
		<h2>Shipping Address</h2>
			<%= fields_for @newaddress do |a| %>
			<p class="form_liner checkout">
				<%= a.label :name, "Name" %>
				<%= a.text_field :name %>
				
				<%= a.label :company, "Company" %>
				<%= a.text_field :company %>
			</p>
			<p class="form_liner checkout">
				<%= a.label :address1, "Address" %>
				<%= a.text_field :address1 %>
				
				<%= a.label :address2, "Address 2" %>
				<%= a.text_field :address2 %>
			</p>
			
			<p class="form_liner checkout">
				<%= a.label :city %>
				<%= a.text_field :city, :style => 'width: 445px;' %>

				<%= a.label :state %>
				<%= a.select :state, options_for_select(us_states) %>
			</p>
			
			<p class="form_liner checkout">
				<%= a.label :zip %>
				<%= a.text_field :zip, :maxlength => 5 %>

				<%= a.label :phone %>
				<%= a.text_field :phone, :maxlength => 14, :placeholder => "999-999-9999" %>
			</p>
		<% end %>


		  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="Waller-Hill Publishing"
	    	      data-amount=<%= @final %>
	        	  data-locale="auto"></script>
		<% end %>
	<% else %>
		<%= form_tag charges_path do %>
		
			<h2>Ship To</h2>
				<%= fields_for @cart do |c| %>
					<%= c.select :address_id, options_for_select(@user_addresses.all.map{|a| [a.array.join(", "), a.id]}) %><br /><br />
				<% end %>
				<%= link_to "Add address", new_address_path, :style => "opacity: .75;" %><br /><br />
			
			

			<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="Waller-Hill Publishing"
	    	      data-amount=<%= @final %>
	        	  data-locale="auto"></script>
		<% end %>
	<% end %>
	<% end %>
</div>