config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :musics, :composers, :music, :welcome, :charges, :tracks, :books, :cart, :cart_items, :addresses

  root 'welcome#index'

	get 'admin' => 'welcome#admin'
	get 'admin/music/:id/tracks' => 'welcome#tracks', as: :admin_tracks
	get 'admin/address-book/user/:id' => 'welcome#address_book', as: :admin_address_book
	get 'admin/user/:id/edit' => 'welcome#admin_edit_user', as: :admin_edit_user
	patch 'admin/user/:id/update' => 'welcome#admin_user_update', as: :admin_user_update
	match 'admin/user/:id' => 'welcome#user_destroy', :via => :delete, as: :admin_destroy_user
	get 'orders/admin/:id/ship' => 'welcome#ship_order', as: :ship_order
	get 'orders/user' => 'welcome#orders', as: :user_orders
	get 'orders/admin' => 'welcome#admin_orders', as: :admin_orders
	get 'orders/admin/order/:id' => 'welcome#admin_view_order', as: :admin_view_order

  get 'users/:id/profile' => 'welcome#user_profile', as: :user_profile
	get 'cart_items' => 'cartitem#create', as: :add_to_cart
	get 'update_cart_item' => 'cartitem#update', as: :update_cart_item

end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user

	validates_presence_of :name, :address1, :city, :state, :zip, :phone
	
	def array
		address = [self.name]
		
		if self.company.present?
			address << self.company
		end
		
		address << self.address1
		
		if self.address2.present?
			address << self.address2
		end
		
		address << self.city
		address << self.state
		address << self.zip
		
		return address
		
	end
	
end

app/models/book.rb
class Book < ActiveRecord::Base

	has_and_belongs_to_many :composers, join_table: "composers_books"
	
	validates_presence_of :title, :description, :isbn, :pubdate, :stock, :can_order
	validates_uniqueness_of :title, :isbn

	has_attached_file :cover, styles: { large: "1350x900", medium: "270x180>", thumb: "180x120>" }, default_url: "/images/:style/missing.jpg"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_one :address
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base

	has_many :products
	belongs_to :cart

end

app/models/charges.rb
class Address < ActiveRecord::Base

	accepts_nested_attributes_for :cart	
end

app/models/composer.rb
class Composer < ActiveRecord::Base

	has_and_belongs_to_many :books, join_table: "composers_books"
	has_and_belongs_to_many :musics, join_table: "musics_composers"

	has_attached_file :photo, styles: { large: "900x900", medium: "200x200>", thumb: "120x120>" }, default_url: "/images/:style/missing.jpg"
		validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/


	validates_presence_of :lname, :bio, :city, :state
	
	def full_name
		"#{fname} #{lname}"
	end
	
	def products
		books + musics
	end

	def to_param
		"#{id}_#{full_name}"
	end
end

app/models/music.rb
class Music < ActiveRecord::Base

	has_and_belongs_to_many :composers, join_table: "musics_composers"
	has_many :tracks
	
	has_attached_file :artwork, styles: { large: "900x809", medium: "185x166>", thumb: "120x108>" }, default_url: "/images/:style/missing.jpg"
	validates_attachment_content_type :artwork, content_type: /\Aimage\/.*\Z/
	
	validates_presence_of :title, :description, :released
	validates_uniqueness_of :title


end

app/models/track.rb
class Track < ActiveRecord::Base

	belongs_to :music
	
	validates_presence_of :title, :music_id, :length, :number, :authors
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses

	validates_presence_of :fname, :lname

  def full_name
    [self.fname, self.lname].join(" ")
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController



end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def us_states
	    [
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
	
	def usd(cents)
		if cents.is_a?(Float) == 0
			cents = cents.to_f
		end
			dollars = (cents / 100) rescue 0
			
		return "$" + number_with_precision(dollars, :precision => 2).to_s
	end
	
	def identify_product(identifier)
		identifier = identifier.to_s
		if identifier.length == 13
			@product = Book.where(:isbn => identifier).first
		else
			@product = Music.where(:barcode => identifier).first
		end
	end
	
	def identify_address(id)
		@address = Address.where(:id => id).first
	end

end

app/helpers/books_helper.rb
module BooksHelper

	def book_params
		params.require(:book).permit(:title, :description, :isbn, :pubdate, :stock, :can_order, :price, :cover, :composer_ids => [])
	end
	
	def stock_check(product)
		if product.stock >= 1
			return "In stock"
		else
			return "Not in stock"
		end
	end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper

	def carttotal(cart)
		@carttotal = 0.00
		@total_items = 0
		
		items = CartItem.where(:cart_id => cart.id)
		
		items.each do |product|
			identify_product(product.product_id)
			
			@item_total = @product.price * product.quantity
			
			@total_items += product.quantity
			
			@carttotal += @item_total
		end
		@carttotal = @carttotal.to_f
		@taxrate = 0.08
		@tax = (@taxrate)*(@carttotal)
		@subtotal = (@carttotal)+(@tax)
		@shipping = (@total_items)*(300)
		@shipping = @shipping.to_f
		@final = @subtotal + @shipping
	end
end

app/helpers/composers_helper.rb
module ComposersHelper
	
end

app/helpers/musics_helper.rb
module MusicsHelper

	    def music_params
			params.require(:music).permit(:title, :desc, :released, :description, :barcode, :stock, :can_order, :digital, :physical, :itunes, :price, :artwork, :composer_ids => [])
	    end

end

app/helpers/tracks_helper.rb
module TracksHelper

	def seconds_to_time(sec)
		hours = sec / 3600
		minutes = sec / 60
		seconds = sec % 60
		
		hours = hours.to_s
		minutes = minutes.to_s
		seconds = seconds.to_s
		time = ""
		
		if hours.to_i > 0
			time = hours + ":"
			
			if minutes.to_i < 10
				minutes = "0" + minutes
			end
		end
		
		if seconds.to_i < 10
			seconds = "0" + seconds
		end
		
		time = time + minutes + ":" + seconds
		
		return time
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def cartitems(cart)
		items = CartItem.where(:cart_id => cart.id).order(:created_at)
	end
	
	def item_count(cart)
		items = CartItem.where(:cart_id => cart.id)
		
		count = 0
		items.each do |i|
			count += i.quantity
		end
		
		return count
	end
	
	def admin_initials(order)
		admin = User.find(order.admin)
		
		return admin.fname[0,1].titleize + admin.lname[0,1].titleize
	end

end

app/views/layouts/_nav.html.erb
<div id="nav_wrapper">
	<%= link_to "Books", books_path, :class => 'nav_element', :id => 'nav_books' %>
	<%= link_to image_tag("logo.png", :id => 'nav_logo'), root_path %>
	<%= link_to "Music", musics_path, :class => 'nav_element', :id => 'nav_music' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Waller-Hill Publishing</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<script type="text/javascript">
	  // This identifies your website in the createToken call below
	  Stripe.setPublishableKey('pk_test_lNKShYpYH1BnQ5it2ap2iGBq');
	  // ...
	</script>
	<%= csrf_meta_tags %>
</head>
<body>
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>
<div id="view_cart"><%= link_to "View Cart", new_charge_path %></div>
<div id="account_buttons">
	<% if current_user %>
		<%= link_to "My Account", user_profile_path(current_user.id) %><br />
		<%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %>
	<% else %>
		<%= link_to "Sign In", new_user_session_path %><br />
		<%= link_to "Create Account", new_user_registration_path %>
	<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Waller-Hill Publishing</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag "https://js.stripe.com/v2/", 'application', 'data-turbolinks-track' => true %>
	<script type="text/javascript">
	  // This identifies your website in the createToken call below
	  Stripe.setPublishableKey('pk_test_lNKShYpYH1BnQ5it2ap2iGBq');
	  // ...
	</script>
	<%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="account_buttons">
	<% if current_user %>
		<%= link_to "My Account", user_profile_path(current_user.id) %><br />
		<%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %>
	<% else %>
		<%= link_to "Sign In", new_user_session_path %><br />
		<%= link_to "Create Account", new_user_registration_path %>
	<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Waller-Hill Publishing</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
		<div style="border: 10px solid rgba(0,0,0,.2); background-color: rgba(155,142,160,.05); padding: 20px;"><!-- wrapper -->
			<div style="width: 100%; padding: 10px; text-align: center;"><!-- topbar -->
				<%= link_to image_tag("logo.png", :style => 'width: 90px;'), root_path %><!-- logo -->
			</div>
			<%= yield %>
		</div>
</body>
</html>